[zorg][lldb-statistics] Set LLDB_ENABLE_LZMA=Off
Getting:
```
In file included from
/Users/ec2-user/jenkins/workspace/test-lldb-statistics/clang-19-src/lldb/source/Host/common/LZMA.cpp:14:
/usr/local/include/lzma.h:294:10: fatal error: 'lzma/version.h' file not
found
  294 | #include "lzma/version.h"
      |          ^~~~~~~~~~~~~~~~
1 error generated.
```

This is also disabled on the incremental bots. So we disable it here
too.