It looks like no one is actually monitoring this builder, so I'm moving it to lab-mini-03. (which is currently offline, needing repairs)
It's failing in the build step:
2013-05-17 17:05:43: building test-suite tools
nt.py:771: fatal error: unable to build tools, aborting!

from build-tools.log:
clang (LLVM option parsing): Unknown command line argument '-vectorize'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-vectorize-slp'?
make[1]: *** [timeit-target] Error 1
make: *** [tools] Error 2

llvm-svn: 182133