[flang-x86_64-windows] Add compiler-rt
On Windows, compiler-rt is required to provide LLVM-emitted functions
that Microsoft's crt does not provide.

Otherwise, this is the error:

flang_rt.runtime.dynamic.lib(binary-to-decimal.cpp.obj) : error LNK2019: unresolved external symbol __udivti3 referenced in function "public: __cdecl Fortran::decimal::BigRadixFloatingPointNumber<64,16>::BigRadixFloatingPointNumber<64,16>(class Fortran::decimal::BinaryFloatingPointNumber<64>,enum Fortran::decimal::FortranRounding)" (??0?$BigRadixFloatingPointNumber@$0EA@$0BA@@decimal@Fortran@@QEAA@V?$BinaryFloatingPointNumber@$0EA@@12@W4FortranRounding@12@@Z)
flang-rt\unittests\Evaluate\reshape.test.exe : fatal error LNK1120: 1 unresolved externals