Removed deprecated code to be ready for buildbot 4.x - buildbot.steps.shell.SetProperty has been renamed to SetPropertyFromCommand. - buildbot.interfaces.WorkerTooOldError has been renamed to WorkerSetupError, but it is unused at all. - BuildStatusGenerator subject parameter has been deprecated: please configure subject in the message formatter. - LLVMFailBuildGenerator argument add_logs have been deprecated. Please use want_logs_content of the passed message formatter. Also GitHubStatusPush.createStatus() in 4.x contains the new parameter `props`. Add `props` to LLVMFailBuildGenerator.createStatus() and LLVMFailGitHubLabeler.createStatus() to avoid builtins.TypeError: LLVMFailGitHubReporter.createStatus() got an unexpected keyword argument 'props' on buildbot 4.x.