OpenMPBuilder: Remove duplicate quotes
These are needed on the shell when manually invoking CMake. Here,
the Configure() command will take care of escaping whitespace and
so the quotes are duplicate and are passed to lit:

   error: argument -v/--verbose: ignored explicit argument

llvm-svn: 318762