Revert "[Fuchsia] Roll base image from jammy to resolute" (#915)
Reverts llvm/llvm-zorg#906
The buildbot in LLVM infra is too old and with newer python
from resolute, it broke due to deprecation of pipes module.
We are seeing errors like
```
  File "/var/lib/buildbot/venv/lib/python3.14/site-packages/buildbot_worker/runprocess.py", line 91, in shell_quote
    import pipes  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pipes'
```
after upgrading to Ubuntu resolute.