[LLVMPoller] Fix an exception in case of changing files in the root (#109)
`project=None` will cause the following exception
```
File "/zorg/buildbot/changes/llvmgitpoller.py", line 188, in _process_changes
    project=",".join(projects) if projects else "llvm-project",
builtins.TypeError: sequence item 0: expected str instance, NoneType found
```
Use a dummy str instead.